---
# tasks file for ansible-role-selinux-disable

- name: Ensure that the selinux packages are installed
  yum:
    name:
      - "{{ ( (ansible_facts.distribution_major_version | int) < 8) | ternary('libselinux-python','python3-libselinux') }}"
      - selinux-policy
    state: present

- name: Disable selinux
  selinux:
    state: disabled
  register: _selinux_module

- name: Attempting to reboot if selinux was active and "selinux_disable_reboot=true" (default is selinux_disable_reboot=false)
  reboot:
    reboot_timeout: "{{ selinux_disable_reboot_timeout }}"
  when:
    - _selinux_module is changed
    - selinux_disable_reboot
